"""
scripts/analyze_representations.py — Representation analysis for §5.3

Produces the empirical evidence behind the paper's "low-pass capacity filter"
hypothesis. For every checkpoint listed in --checkpoint_specs, this script:

  1. Loads the model + weights.
  2. Forwards the val-set images through it and stacks the bottleneck
     feature maps (B, C, 8, 8) into a (N*64, C) matrix, where N is the
     val-set size and C is the bottleneck channel count.
     - HA-Net  bottleneck is (512, 8, 8)  -> 512 features per spatial token
     - EdgeUNet bottleneck is (192, 8, 8) -> 192 features per spatial token
  3. Runs PCA on the (N*64, C) feature matrix and reports the cumulative
     explained-variance curve, the number of components to reach 90 / 95 / 99 %
     of variance, and the participation-ratio effective rank
     PR = (sum sigma_i)^2 / (sum sigma_i^2).
  4. Computes the singular spectrum of the Hop-2 projector h_psi
     (the 192 -> 512 channel conv inside Hop2DistillationLoss) for any
     checkpoint that stores it, as a direct test of the rank-bottleneck
     argument.

Outputs
-------
  <out_dir>/cumulative_variance.pdf  — paper figure, one curve per checkpoint
  <out_dir>/effective_rank.json      — numerical summary (PR, k_90/95/99, etc.)
  <out_dir>/projector_spectra.pdf    — Hop-2 projector singular values

Local dry-run
-------------
For pipeline verification on synthetic data, point --busi_root at the
test_data/busi/ directory generated by scripts/make_mock_data.py. The
resulting numbers are NOT meaningful for the paper — only the pipeline
mechanics are validated. The real figure must come from a Kaggle run
against the actual BUSI val split.
"""

from __future__ import annotations

import argparse
import json
import logging
import re
import sys
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision.transforms.functional as TF
from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from src.models import HANet
from src.edgeunet import EdgeUNet


logging.basicConfig(
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
    level=logging.INFO,
)
log = logging.getLogger("analyze_representations")


# --------------------------------------------------------------------------- #
# BUSI val image discovery (matches the existing trainers' protocol)          #
# --------------------------------------------------------------------------- #

_MASK_RE = re.compile(r"_mask(?:_\d+)?$", re.IGNORECASE)
BUSI_CLASSES = ("benign", "malignant")


def discover_busi_pairs(root: Path) -> List[Path]:
    """Return image paths only (we don't need masks for representation analysis)."""
    imgs: List[Path] = []
    for cls in BUSI_CLASSES:
        cls_dir = root / cls
        if not cls_dir.is_dir():
            continue
        for img_path in sorted(cls_dir.glob("*.png")):
            if _MASK_RE.search(img_path.stem):
                continue
            imgs.append(img_path)
    return imgs


def deterministic_val_subset(images: List[Path], val_frac: float, seed: int) -> List[Path]:
    rng = np.random.RandomState(seed)
    idx = np.arange(len(images))
    rng.shuffle(idx)
    n_val = int(round(len(images) * val_frac))
    return [images[i] for i in sorted(idx[:n_val].tolist())]


@torch.no_grad()
def load_image_batch(paths: List[Path], image_size: int, device: torch.device) -> torch.Tensor:
    """Load a list of images, resize to image_size x image_size, return (B, 3, H, W)."""
    tensors = []
    for p in paths:
        im = Image.open(p).convert("RGB").resize((image_size, image_size), Image.BILINEAR)
        t = TF.pil_to_tensor(im).float().div_(255.0)
        tensors.append(t)
    return torch.stack(tensors, dim=0).to(device)


# --------------------------------------------------------------------------- #
# Checkpoint loading                                                          #
# --------------------------------------------------------------------------- #

def load_hanet(checkpoint_path: Path, device: torch.device) -> nn.Module:
    state = torch.load(checkpoint_path, map_location=device, weights_only=False)
    if isinstance(state, dict) and "model" in state and isinstance(state["model"], dict):
        state = state["model"]
    model = HANet(in_channels=3, num_classes=1).to(device)
    model.load_state_dict(state, strict=True)
    model.eval()
    return model


def load_edgeunet(checkpoint_path: Path, device: torch.device) -> nn.Module:
    state = torch.load(checkpoint_path, map_location=device, weights_only=False)
    # EdgeUNet checkpoints from train_baseline.py / train_a1_direct.py / train_hop2.py
    # use either "model" or "student" as the state_dict key.
    for k in ("model", "student"):
        if isinstance(state, dict) and k in state and isinstance(state[k], dict):
            state = state[k]
            break
    model = EdgeUNet(in_channels=3, num_classes=1).to(device)
    model.load_state_dict(state, strict=True)
    model.eval()
    return model


def maybe_load_projector(checkpoint_path: Path, device: torch.device) -> torch.Tensor | None:
    """Return the projector conv weight (out=512, in=192, 1, 1) if present, else None."""
    state = torch.load(checkpoint_path, map_location=device, weights_only=False)
    if isinstance(state, dict) and "projector" in state and isinstance(state["projector"], dict):
        proj = state["projector"]
        # Expect a single conv weight under "conv.weight" (per src.loss_hop1/2 layout).
        for k, v in proj.items():
            if k.endswith("conv.weight") or k == "weight":
                return v.detach().cpu().float()
        # Fallback: take the first 4D tensor.
        for v in proj.values():
            if torch.is_tensor(v) and v.dim() == 4:
                return v.detach().cpu().float()
    return None


# --------------------------------------------------------------------------- #
# Bottleneck feature extraction                                               #
# --------------------------------------------------------------------------- #

@torch.no_grad()
def extract_bottleneck(
    model: nn.Module,
    images: List[Path],
    image_size: int,
    device: torch.device,
    batch_size: int = 8,
) -> np.ndarray:
    """Run model on every image, stack bottleneck features into (N_tokens, C).

    The bottleneck is (B, C, 8, 8) -> we flatten spatial to give B*64 tokens
    of dimension C. PCA is then computed across the row dimension.
    """
    rows: List[np.ndarray] = []
    for i in range(0, len(images), batch_size):
        batch = images[i : i + batch_size]
        x = load_image_batch(batch, image_size, device)
        _, bottleneck = model(x)   # (B, C, 8, 8)
        bottleneck = bottleneck.float().cpu()
        # (B, C, 8, 8) -> (B*64, C)
        rows.append(bottleneck.permute(0, 2, 3, 1).reshape(-1, bottleneck.shape[1]).numpy())
    return np.concatenate(rows, axis=0)


# --------------------------------------------------------------------------- #
# PCA + effective rank                                                        #
# --------------------------------------------------------------------------- #

def pca_cumulative_variance(features: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    """Returns (singular_values, cumulative_explained_variance) sorted desc."""
    # Centre.
    x = features - features.mean(axis=0, keepdims=True)
    # SVD on the (N, C) matrix; singular values ~ sqrt(N-1) * std deviations.
    u, s, vt = np.linalg.svd(x, full_matrices=False)
    var = s ** 2
    cumvar = np.cumsum(var) / var.sum()
    return s, cumvar


def participation_ratio(singular_values: np.ndarray) -> float:
    """PR effective rank: (sum lambda_i)^2 / sum lambda_i^2 with lambda = s^2."""
    var = singular_values.astype(np.float64) ** 2
    return float((var.sum() ** 2) / (var ** 2).sum())


def k_for_threshold(cumvar: np.ndarray, threshold: float) -> int:
    """Smallest k such that cumvar[k-1] >= threshold."""
    idx = np.searchsorted(cumvar, threshold, side="left")
    return int(idx + 1)  # 1-indexed component count


# --------------------------------------------------------------------------- #
# Main                                                                        #
# --------------------------------------------------------------------------- #

DEFAULT_CHECKPOINTS = {
    # Friendly key -> (model_type, path-glob from --runs_root)
    "B2  HA-Net (sup)":              ("hanet",   "b2_hanet_seed{seed}/hanet_baseline_best.pt"),
    "A3-h1  HA-Net (lambda=1.0)":    ("hanet",   "a3_hop1_seed{seed}/hanet_best.pt"),
    "B1  EdgeUNet (sup)":            ("edgeunet","b1_edgeunet_seed{seed}/edgeunet_baseline_best.pt"),
    "A2  EdgeUNet (HA-Net distill)": ("edgeunet","a2_seed{seed}/student_best.pt"),
    "A3  EdgeUNet (TAKD)":           ("edgeunet","a3_hop2_seed{seed}/student_best.pt"),
}


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="PCA + effective-rank representation analysis.")
    p.add_argument("--busi_root", type=Path, required=True,
                   help="Root of BUSI dataset with benign/ and malignant/ subdirs. "
                        "For pipeline-verification dry runs, point this at test_data/busi/.")
    p.add_argument("--runs_root", type=Path, required=True,
                   help="Parent of seed-keyed run dirs (e.g. kaggle_run_3/runs_multiseed/).")
    p.add_argument("--out_dir", type=Path, required=True)
    p.add_argument("--seed", type=int, default=20260530,
                   help="Which seed's checkpoints to analyse. Default 20260530.")
    p.add_argument("--val_frac", type=float, default=0.2)
    p.add_argument("--image_size", type=int, default=256)
    p.add_argument("--batch_size", type=int, default=8)
    p.add_argument("--device", type=str, default=None,
                   help="cuda / mps / cpu. Auto if None.")
    p.add_argument("--no_plot", action="store_true",
                   help="Skip matplotlib output (numeric JSON only).")
    return p.parse_args()


def main() -> None:
    args = parse_args()
    args.out_dir.mkdir(parents=True, exist_ok=True)

    if args.device:
        device = torch.device(args.device)
    elif torch.cuda.is_available():
        device = torch.device("cuda")
    else:
        device = torch.device("cpu")
    log.info("device=%s", device)

    # ---- Val subset ----
    images = discover_busi_pairs(args.busi_root)
    if not images:
        raise RuntimeError(f"No BUSI images discovered under {args.busi_root}")
    val_images = deterministic_val_subset(images, args.val_frac, args.seed)
    log.info("dataset: total=%d  val=%d (seed=%d, val_frac=%.2f)",
             len(images), len(val_images), args.seed, args.val_frac)

    # ---- Per-checkpoint feature extraction + PCA ----
    summary: Dict[str, Dict] = {}
    pca_results: Dict[str, Tuple[np.ndarray, np.ndarray]] = {}

    for label, (mtype, sub) in DEFAULT_CHECKPOINTS.items():
        ckpt = args.runs_root / sub.format(seed=args.seed)
        if not ckpt.is_file():
            log.warning("[skip] %s — checkpoint missing at %s", label, ckpt)
            continue

        log.info("[%s] loading %s", label, ckpt)
        if mtype == "hanet":
            model = load_hanet(ckpt, device)
        else:
            model = load_edgeunet(ckpt, device)

        feats = extract_bottleneck(model, val_images, args.image_size, device,
                                   batch_size=args.batch_size)
        del model
        if device.type == "cuda":
            torch.cuda.empty_cache()

        sv, cumvar = pca_cumulative_variance(feats)
        pr = participation_ratio(sv)
        k90 = k_for_threshold(cumvar, 0.90)
        k95 = k_for_threshold(cumvar, 0.95)
        k99 = k_for_threshold(cumvar, 0.99)

        summary[label] = {
            "checkpoint": str(ckpt),
            "n_tokens": int(feats.shape[0]),
            "ambient_dim": int(feats.shape[1]),
            "participation_ratio": pr,
            "k_for_90pct": k90,
            "k_for_95pct": k95,
            "k_for_99pct": k99,
            "top_10_singular_values": [float(x) for x in sv[:10]],
        }
        pca_results[label] = (sv, cumvar)

        log.info("[%s] tokens=%d  dim=%d  PR=%.1f  k90=%d  k95=%d  k99=%d",
                 label, feats.shape[0], feats.shape[1], pr, k90, k95, k99)

    # ---- Hop-2 projector spectrum (rank-192 bottleneck argument) ----
    proj_specs = []
    for label, (mtype, sub) in DEFAULT_CHECKPOINTS.items():
        if mtype != "edgeunet" or "EdgeUNet" not in label:
            continue
        ckpt = args.runs_root / sub.format(seed=args.seed)
        if not ckpt.is_file():
            continue
        W = maybe_load_projector(ckpt, device)
        if W is None:
            continue
        # W shape: (out, in, 1, 1) for a 1x1 conv → reshape to (out, in)
        if W.dim() == 4:
            W = W.squeeze(-1).squeeze(-1)
        # SVD of the projector matrix (numpy)
        W_np = W.cpu().numpy().astype(np.float64)
        u, sv_proj, vt = np.linalg.svd(W_np, full_matrices=False)
        var = sv_proj ** 2
        cumvar_proj = np.cumsum(var) / var.sum()
        pr_proj = participation_ratio(sv_proj)
        proj_specs.append((label, sv_proj, cumvar_proj, pr_proj))
        log.info("[projector] %s  shape=%s  PR=%.1f  k90=%d  k99=%d",
                 label, tuple(W.shape), pr_proj,
                 k_for_threshold(cumvar_proj, 0.90),
                 k_for_threshold(cumvar_proj, 0.99))

    # ---- Write JSON ----
    out_json = args.out_dir / "effective_rank.json"
    out_json.write_text(json.dumps(summary, indent=2))
    log.info("wrote %s", out_json)

    # ---- Plot ----
    if not args.no_plot:
        try:
            import matplotlib
            matplotlib.use("Agg")  # headless
            import matplotlib.pyplot as plt

            # Figure 1: cumulative variance per checkpoint
            fig, ax = plt.subplots(figsize=(6.0, 4.2))
            for label, (sv, cumvar) in pca_results.items():
                style = "-" if "HA-Net" in label or "B2" in label or "A3-h1" in label else "--"
                ax.plot(np.arange(1, len(cumvar) + 1), cumvar, style, label=label, linewidth=1.5)
            ax.axhline(0.90, linestyle=":", linewidth=0.8, color="gray")
            ax.axhline(0.99, linestyle=":", linewidth=0.8, color="gray")
            ax.set_xlabel("PCA component index")
            ax.set_ylabel("cumulative explained variance")
            ax.set_title(f"Bottleneck PCA — BUSI val (seed={args.seed})")
            ax.set_xscale("log")
            ax.set_ylim(0, 1.02)
            ax.grid(alpha=0.3)
            ax.legend(loc="lower right", fontsize=8)
            fig.tight_layout()
            fig.savefig(args.out_dir / "cumulative_variance.pdf")
            fig.savefig(args.out_dir / "cumulative_variance.png", dpi=140)
            plt.close(fig)
            log.info("wrote %s", args.out_dir / "cumulative_variance.pdf")

            # Figure 2: projector spectra
            if proj_specs:
                fig, ax = plt.subplots(figsize=(6.0, 4.2))
                for label, sv_proj, cumvar_proj, pr_proj in proj_specs:
                    ax.plot(np.arange(1, len(sv_proj) + 1),
                            sv_proj / sv_proj.max(),
                            label=f"{label} (PR={pr_proj:.1f})", linewidth=1.5)
                ax.set_xlabel("singular value index")
                ax.set_ylabel("normalised singular value")
                ax.set_title(f"Hop-2 projector h_psi spectrum  (seed={args.seed})")
                ax.set_yscale("log")
                ax.grid(alpha=0.3)
                ax.legend(loc="upper right", fontsize=8)
                fig.tight_layout()
                fig.savefig(args.out_dir / "projector_spectra.pdf")
                fig.savefig(args.out_dir / "projector_spectra.png", dpi=140)
                plt.close(fig)
                log.info("wrote %s", args.out_dir / "projector_spectra.pdf")
        except ImportError:
            log.warning("matplotlib not available; skipping plots")

    # ---- Console headline ----
    print()
    print("=" * 70)
    print("HEADLINE — copy this into the paper's §5.3:")
    print("=" * 70)
    for label, d in summary.items():
        print(f"  {label:<35s}  PR={d['participation_ratio']:>6.1f}   "
              f"k_90%={d['k_for_90pct']:>4d}   k_99%={d['k_for_99pct']:>4d}   "
              f"(C={d['ambient_dim']})")
    print("=" * 70)


if __name__ == "__main__":
    main()
